services:
  db:
    image: postgres:latest
    container_name: db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: username 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inovare
    restart: always
    
